### ISSUE TITLE
No icon displayed on Post Loop Builder's Load More button

### ISSUE THREAD

**Issue by mblmg** [soflyy/breakdance-bugs#1034]
Wordpress version: 6.4.2
Theme: Astra 4.6.2
Breakdance Version: 1.7

**Issue:**
In the frontend, the Post Loop Builder's Load More Button displays empty space instead of the icon that was set in the backend.

**Steps to reproduce:**
1. In Breakdance, add a post loop builder element
2. Set Pagination to Load More Button
3. Set Custom Icon in Pagination > Load More Button > Custom > Icon
4. Save Page and look at it in frontend

Expected behavior: Icon is displayed on the button
Actual behavior: Icon is NOT displayed but there is empty space where the icon should be

This issue is new because it disappears when I roll back Breakdance to 1.6.1

**Comment by breakdancemoderator** [comment]
Thank you for submitting your report and for helping us improve Breakdance. We have reviewed your submission, but currently, we're unable to reproduce the issue based on the information provided.

To ensure that your issue is addressed as efficiently as possible, we kindly request that you contact our dedicated support team by emailing [support@breakdance.com](mailto:support@breakdance.com). Our team is well-equipped to dive deeper into specific scenarios and provide personalized assistance you may need.
