### ISSUE TITLE
WP Menu > Dropdowns > Links > Hover background doesn't work.

### ISSUE THREAD

**Issue by rodolphebertozzo** [soflyy/breakdance-bugs#1046]
The color selected for this control does not apply to the elment.

**Comment by breakdancemoderator** [comment]
Thank you for submitting your report and for helping us improve Breakdance. We have reviewed your submission, but currently, we're unable to reproduce the issue based on the information provided.

To ensure that your issue is addressed as efficiently as possible, we kindly request that you contact our dedicated support team by emailing [support@breakdance.com](mailto:support@breakdance.com). Our team is well-equipped to dive deeper into specific scenarios and provide personalized assistance you may need.
