### ISSUE TITLE
V.2 doesn't show anything on clean install

### ISSUE THREAD

**Issue by mechaphone** [soflyy/breakdance-bugs#1074]
Breakdance Beta 2.0
Safari
wp 6.5.3

When I do a wp clean install I am not able to enter the breakdance editor. Not when I create a page but also not global blocks etc.
All remains empty.

**Comment by breakdancemoderator** [comment]
Thank you for submitting your report and for helping us improve Breakdance. We have reviewed your submission, but currently, we're unable to reproduce the issue based on the information provided.

To ensure that your issue is addressed as efficiently as possible, we kindly request that you contact our dedicated support team by emailing support@breakdance.com. Our team is well-equipped to dive deeper into specific scenarios and provide personalized assistance.
