### ISSUE TITLE
Postloop Builder - Filtering did not work

### ISSUE THREAD

**Issue by braeu71** [soflyy/breakdance-bugs#1090]
-Add a post loob
-set your query
-the posts are displayed correctly
![Screenshot 2024-06-09 182313](https://github.com/soflyy/breakdance-bugs/assets/7048096/ef82d512-8e17-442c-aa95-300c442102b3)

-enable the filter bar

> -the following error appears:
> --An error occurred while running an inline script from "onMountedElement" for element with ID "115". Error: "TypeError: Isotope is not a constructor"--

**after an update to beta 2 the error no longer appears, but unfortunately the filtering still does not work** 

-It does not change even if the type of the filter bar is selected correctly.

**Comment by breakdancemoderator** [comment]
Thank you for submitting your report and for helping us improve Breakdance. We have reviewed your submission, but we're currently unable to reproduce the issue based on the information provided.

To ensure that your issue is addressed as efficiently as possible, we kindly request that you contact our dedicated support team by emailing [support@breakdance.com](mailto:support@breakdance.com). Our team is well-equipped to dive deeper into specific scenarios and provide personalized assistance.
