### ISSUE TITLE
Beta2 has no dashboard or edit possibilities

### ISSUE THREAD

**Issue by mechaphone** [soflyy/breakdance-bugs#1102]
Installed Beta2 over v1.7.0 and clicked Migrate Meta
The website is working as before.
In the backend I am not able to work in BD anymore. The menu or anything else remains empty. See screenshot
Also CPT remains empty and edit with Breakdance has no result and returns a empty page.
Cleared the cache (as far as I know how to)on the server. No result.

![Scherm­afbeelding 2024-06-19 om 10 45 20](https://github.com/soflyy/breakdance-bugs/assets/48671001/0eb3bca0-b69f-4fb5-bd05-8b8bce85f3da)

Breakdance-v2.0.0-beta.2
Safari 16.3 (18614.4.6.1.6)
Chrome 126.0.6478.62 (Officiële build) (arm64)

**Comment by breakdancemoderator** [comment]
Thank you for submitting your report and for helping us improve Breakdance. We have reviewed your submission, but currently, we're unable to reproduce the issue based on the information provided.

To ensure that your issue is addressed as efficiently as possible, we kindly request that you contact our dedicated support team by emailing [support@breakdance.com](mailto:support@breakdance.com). Our team is well-equipped to dive deeper into specific scenarios and provide personalized assistance.
