### ISSUE TITLE
Shop filter by attribute not appear

### ISSUE THREAD

**Issue by mredodos** [soflyy/breakdance-bugs#1185]
Im editing the shop page template and im try to set shopfilter by attribute.

But it seems the shopfilters by attribute not appear, if i set two time price filter ,for example, appears two time, but when i set an attribute don't. 

![image](https://github.com/user-attachments/assets/dfb0fc33-5e72-487e-970b-8d4394283d1d)

i have try a plugin conflict test but not solve the issue

**Comment by breakdancemoderator** [comment]
Thank you for submitting your report and for helping us improve Breakdance. We have reviewed your submission, but currently, we're unable to reproduce the issue based on the information provided.

To ensure that your issue is addressed as efficiently as possible, we kindly request that you contact our dedicated support team by emailing [support@breakdance.com](mailto:support@breakdance.com). Our team is well-equipped to dive deeper into specific scenarios and provide personalized assistance.
