### ISSUE TITLE
Some issues with styling submit button form element

### ISSUE THREAD

**Issue by adkoen** [soflyy/breakdance-bugs#210]
I've added an icon to the primary button global styles.
I now created a form where I don't want an icon on the submit button. It looks like in the current setup this isn't possible. I guess the submit button defaults to the primary button and I don't have the choice to, for instance, pick the secondary button as submit button. In summary, I can't have a form submit button without icon if the global primary button already has an icon assigned.
Now that I'm here, we need more global buttons than primary and secondary. I'm thinking about a regular, less important link button (light gray for instance, where the primary and/or secondary buttons have the brand colors), an outline button, an inverted button for on dark backgrounds and so on... Would be nice if we could make more global button presets just like the typography presets, or some other workflow that gives the functionality of more global button styles.

**Comment by louisreingold** [comment]
This is a good idea. Since it is a feature request, please post it at https://breakdance.canny.io/

> It looks like in the current setup this isn't possible

If you insist on adding an icon to your primary button global styles, you can use custom CSS to remove it from the form only. But my advice is not to add an icon to your primary button global styles if you don't want it on all of the buttons.
