### ISSUE TITLE
Heading set dynamically to post title - &nbsp; in dynamically set text 

### ISSUE THREAD

**Issue by MediaGozo** [soflyy/breakdance-bugs#261]
Heading Title not working properly

Under certain circumstances the heading text is not reacting resonsivly..

Please see:

https://www.loom.com/share/2298d2f1bc74473ea7e54e1951a553ba

**Comment by louisreingold** [comment]
The fact that resetting the title in the WP admin fixed the problem in Breakdance leads me to believe that for whatever reason, your post title, as it was saved in the WP database when you recorded the original video, had an &nbsp; in it. 

Any ideas why that could have been the case? Gutenberg bug? 

If you figure out steps to reproduce this or anything that indicates the issue is with Breakdance, please open another issue.
