### ISSUE TITLE
Dual Heading - bug on load

### ISSUE THREAD

**Issue by louisreingold** [soflyy/breakdance-bugs#29]
From Facebook: https://www.facebook.com/groups/breakdanceofficial/posts/5183197798382140/

![image](https://user-images.githubusercontent.com/6425257/175891859-0da1174c-5616-4717-90ea-69785e202292.png)

![image](https://user-images.githubusercontent.com/6425257/175891984-37f05edc-b526-4b45-a7fa-97e9e6a5c09f.png)

"Hello, dual heading is buggy(see first img). First site load the highlight is bit off to left. reload and will fix it(see second img). But if hard refresh again (ctr + f5) the issue comes back"

**Comment by louisreingold** [comment]
@neeckola, can I get a page URL where this problem takes place? I know I've seen it before but I can't manage to reproduce it.

**Comment by neeckola** [comment]
@louisreingold unfortunately I don't remember seeing this issue on live, only screenshots. Searched the group, but couldn't find it. Comments on FB post are closed, but maybe you should reopen and ask OP for the link.

**Comment by louisreingold** [comment]
I see. I thought you were the OP. Thanks.

**Comment by StefanPavlov23** [comment]
@louisreingold Hi Louise, The bug is still tnere in 1.1 BETA, so here is a link where the bug is visible: https://promos.cadassist.net/
For me it is happening randomly. Тhe site is on Siteground hosting with pre-installed SG Optimizer which is activated, but not set up: 
![image](https://user-images.githubusercontent.com/110225636/203339973-5c0de5b1-421c-4778-9681-03ab90fabf13.png)

**Comment by a-dubiel** [comment]
✋🏻 Hey, thanks for your report. This has been addressed in the latest release.
