### ISSUE TITLE
Woocommerce global style setting not working

### ISSUE THREAD

**Issue by mikehenze** [soflyy/breakdance-bugs#326]
The following global style setting are not working:

Woocommerce > Other > Wrappers > Border radius and shadow

And some options are not available in global styling:
Woocommerce > Layout > Between products
Woocommerce > Product wrapper > Padding > Padding
Woocommerce > Product wrapper > Align content

**Comment by louisreingold** [comment]
I wasn't not able to reproduce the non-working options. With step-by-step instructions to reproduce (do they not work for a specific element when used on a specific page?) I will re-open.

As far as spacing, we have various spacing settings in the WooCommerce global styles. We don't intend to add more, since all (almost all) spacing is supposed to be controlled by the existing global spacing settings. If not, please show the specific element (and which part of it, i.e. "spacing between button and qty input") that won't respect the spacing set in the global styles and we'll fix that.
