### ISSUE TITLE
Difference in default product page cart button and template product page cart button.

### ISSUE THREAD

**Issue by vlmsn** [soflyy/breakdance-bugs#444]
I came across this trying to use a plugin called Extra Product Options. It's for creating a custom input before the 'add to cart' button.

By default it works fine. 
![image](https://user-images.githubusercontent.com/45251442/194703690-192d0f3d-1f46-4ad0-af7f-23a7afc52e60.png)

But once I make an actual template using the product builder it doesn't display the custom input anymore. Just the add to cart button. Plus I noticed that it has a div with a class of 'bde-wooproductcartbutton' wrapping over it. 

I don't know if it's even an actual bug, but its kind of strange the plugin works with the "default"  BD woo styling.

**Comment by louisreingold** [comment]
I wonder what hook we aren't firing.

**Comment by breakdancemoderator** [comment]
Thank you for submitting your report and for helping us improve Breakdance. We have reviewed your submission, but currently, we're unable to reproduce the issue based on the information provided.

To ensure that your issue is addressed as efficiently as possible, we kindly request that you contact our dedicated support team by emailing [support@breakdance.com](mailto:support@breakdance.com). Our team is well-equipped to dive deeper into specific scenarios and provide personalized assistance you may need.

**Comment by breakdancemoderator** [comment]
Based on the provided screenshot we did I fix a bug where the quantity input leaves an empty space on the left side of the add to cart button, and that fix is available in 2.0 beta 1.
