### ISSUE TITLE
Release Candidates Showing as updates in stable version

### ISSUE THREAD

**Issue by ReflectedReality648** [soflyy/breakdance-bugs#581]
Release candidates are showing up as updates in Breakdance without the show beta box being ticked. This is happening across all of my sites.

Many thanks,

Phil

**Comment by aadlung** [comment]
Any updates here? I can't update using my automations as there's no way to update to a specific version in wordpress...

**Comment by louisreingold** [comment]
We're not able to reproduce this in our tests, but it's probably real, or at least it was back in January.

We did make some changes to the licensing logic since then though.

But at least three people have reported this in January. It's now June and we haven't heard about it again, but if it does happen agian, please email support@breakdance.com if it happens again and don't update. We'd love to take a look.
