### ISSUE TITLE
z-index has no effect on header/table of contents

### ISSUE THREAD

**Issue by ajlcomputers** [soflyy/breakdance-bugs#640]
I’m trying to use the table of contents and a sticky header and by default the TOC goes over the header so I set the z-index of both to try and change this behaviour and it made no difference.

it seems that the header already has a z-index of 100 and the toc has a z-index of 999 and neither of these are overwritten by the settings that we input.

**Comment by LambMediaGroup** [comment]
I've also found that the lightbox has a z-index set to something like 1040 so that also needs to be taken into account when changing the z-index of the other items.

It would be handy if hard coded things like this showed in the editing window so that we know what's assigned to what elements and can easily change them. It makes life so hard when things are hard coded and not shown in the editor.

Thanks.

**Comment by a-dubiel** [comment]
✋🏻 Hey, thank you for your patience. The issue has been addressed in the latest release. Please go to https://breakdance.com/portal/downloads/ to download Breakdance 1.3. Thank you for helping us improve Breakdance.
