### ISSUE TITLE
Image Element doesnt apply Height and Object-fit

### ISSUE THREAD

**Issue by quentalstudio** [soflyy/breakdance-bugs#675]
I simply put the image element with 500px height and object-fit:cover, but in the front-end it doesn't assume the values.

<img width="440" alt="Screenshot 2023-01-23 at 23 50 25" src="https://user-images.githubusercontent.com/122744933/214178230-71dba2b6-b24b-4655-bef2-e1a6e4ef3c38.png">
<img width="741" alt="Screenshot 2023-01-23 at 23 50 15" src="https://user-images.githubusercontent.com/122744933/214178092-19d16dd0-37be-4973-ae26-cb511cf2e23d.png">
<img width="163" alt="Screenshot 2023-01-23 at 23 51 19" src="https://user-images.githubusercontent.com/122744933/214178106-d074524e-6679-4ca6-b0fe-1ce2a8b5e42e.png">

**Comment by breakdancemoderator** [comment]
Thank you for submitting your report and for helping us improve Breakdance. We have reviewed your submission, but currently, we're unable to reproduce the issue based on the information provided.

To ensure that your issue is addressed as efficiently as possible, we kindly request that you contact our dedicated support team by emailing support@breakdance.com. Our team is well-equipped to dive deeper into specific scenarios and provide personalized assistance.
