### ISSUE TITLE
Advanced Slider Layer Item Position

### ISSUE THREAD

**Issue by Bonnie-Clyde** [soflyy/breakdance-bugs#689]
**What version of Breakdance are you using?**
 v1.2.1

**What browser are you using?**
FireFox

**What operating system are you using?**
Windows

**Problem/Bug or Designed that way?**
When applying a Custom Position to a Item on top of an Item
First Item is a Background Image
Second Item is an Image(Drone)
When applying a Left Position (px) the first image(background) moves
When applying a Left Position (%) the Second Item(drone) moves.
See images.

![Screenshot 2023-02-09 at 19-07-07 Breakdance New Home](https://user-images.githubusercontent.com/111174477/217769761-6b951b9f-f416-4867-ba64-28d6bfe42cf4.png)
![Screenshot 2023-02-09 at 19-07-29 Breakdance New Home](https://user-images.githubusercontent.com/111174477/217769774-5b101671-192f-4d56-ba33-7a67a39aebe3.png)

**Comment by TeoWin** [comment]
I learned (after quite some time) that the image that you see in the designer is scaled down because of the sections to the left and right. But I suppose the drone images are positioned based on the real left of the screen (not the right part of the settings div but 100% wide body div). I spent quite some time with images that won't fit when I design them for my screen and so I found out that the middle of my image is not in the middle because the designer is too small.

In the designer you see your design in about 60-70% of the screen (the border with the shadow) instead of 100%. I don't understand why the design panels are fixed so the eat up space. If they would float or be aligned to the top or the bottom, the design would be full width.

**Comment by Bonnie-Clyde** [comment]
If the bottom item image position isn't set, than changing the second item position changes the first item position. 
(ie. Items not Elements)

![Screenshot 2023-03-06 at 14-43-58 Breakdance Sample Page](https://user-images.githubusercontent.com/111174477/223021369-f4ae21de-9d0b-4610-b817-21ccc9e5d1f3.png)
