### ISSUE TITLE
403s on Cloudways and Other Providers

### ISSUE THREAD

**Issue by louisreingold** [soflyy/breakdance-bugs#7]
A number of users have reported 403s on Cloudways and Other Providers

-----

Here's the fix:

> From the top menu bar, open Servers.
> 
> Then, choose the server where your desired application is deployed.
> Next, click www.
> 
> Choose your application’s name.
> Select Application Settings in the sidebar menu
> Scroll down, and set "Direct PHP Files Access" to "enable"
> 
> ‘Disable’ means that direct access to PHP files is restricted; whereas, ‘Enable’ means that direct access to PHP files is allowed.
> 
> The Builder runs directly from a PHP file in Breakdance's plugin directory, so we need this option enabled for our plugin to work.
> 
> https://www.loom.com/share/87b61ff71c8149e487079ad2e88f3b7c
> 

We'll need to either change the way we open the builder or work with these hosts to avoid this problem.

**Comment by Grezvany13** [comment]
I'm sorry to say, but that is not a "fix" but adding a security risk to the website and server.

Hosters like Cloudways have this feature enabled for good reasons, and most (if not all) security plugins will do the same (Securi, iThemes, etc.).

Plugins which require direct access usually are far from secure because they bypass the default handling of WordPress (and security plugins).

The only fix possible to change the way that the builder is being opened.

**Comment by louisreingold** [comment]
Similar problems on SiteGround and DigitalOcean are being reported

**Comment by louisreingold** [comment]
Fixed in https://breakdance.com/breakdance-alpha-2/

**Comment by louisreingold** [comment]
Just kidding. This still could happen on certain providers for the Breakdance > Templates / Headers / Footers / Global Blocks / Popups screen, and for the Regenerate Cache button at Breakdance > Settings > Tools.

**Comment by louisreingold** [comment]
This is fixed.
