### ISSUE TITLE
Mini-Cart displayed price is wrong when using weight based pricing

### ISSUE THREAD

**Issue by lockedm** [soflyy/breakdance-bugs#788]
**What version of Breakdance are you using?**

v1.2.1, v1.3 beta 1

**What browser are you using?**

Edge, Opera

**What operating system are you using?**

Windows

**Reproduction  Steps**

- install the 'weight based pricing' plugin for woocommerce
- configure a product to use weight based pricing
- ensure the increment is a fraction e.g. 0.01
- add a product to the basket with a weight of e.g. 0.15
- the product price displayed should be 0.15 * the unit price, instead the unit price is displayed
- note that the overall cart sub-total price is correct

Also note that the correct price flashes on screen briefly and is then replaced with the incorrect price. The correct prices are displayed on the main cart page and on the checkout page.

**Reproduction Video**

https://recordings.webxdesign.studio/recordings/5F4Chfb9DbpBp2QqiVQk

**Comment by louisreingold** [comment]
After further investigation, we recommend contacting the team behind that plugin. We reviewed it but it only has 400 installs and, more importantly, it doesn't use the correct WooCommerce hooks. It's not due to an issue with the Breakdance Mini Cart element.

If the developer of that plugin wishes to update the plugin to use correct hooks, it's likely the Breakdance Mini Cart element will work with it. If not, we're happy to re-open this.
