### ISSUE TITLE
Custom Shape Divider is Putting an SVG within an SVG

### ISSUE THREAD

**Issue by thekendog** [soflyy/breakdance-bugs#956]
I'm on 1.5 and using the `breakdance_shape_dividers` filter.  The resulting output is putting my custom SVG within another SVG element.

https://share.cleanshot.com/NjCfq4mX

**Comment by louisreingold** [comment]
Your file should be in the same format as Breakdance's included shape dividers. For an example: 
 - https://github.com/soflyy/breakdance-developer-docs/blob/master/hooks/my-divider.svg
 - https://github.com/soflyy/breakdance-developer-docs/blob/master/hooks/shape-dividers.md

Note that there is no `svg` tag present.

We should have picked a different extension for the file instead of .svg.
